[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
ignore = ["E203", "E501", "F481"]
exclude = ["__pycache__", ".git", ".venv"]