# orchestrator/Dockerfile
FROM python:3.9-slim

WORKDIR /app
COPY src/Orchestrator/requirements.txt ./src/Orchestrator/requirements.txt
RUN pip install -r ./src/Orchestrator/requirements.txt

# 复制应用代码
COPY src/ ./src/
COPY __main__.py ./__main__.py  

# CMD ["python", "src/Orchestrator/redis_main.py"]
CMD ["/bin/bash"]