# orchestrator/Dockerfile
FROM python:3.9-slim

WORKDIR /app
COPY src/Orchestrator/requirements.txt ./src/Orchestrator/requirements.txt
RUN pip install -r ./src/Orchestrator/requirements.txt

COPY . .

CMD ["python", "redis_main.py"]